language: python

python:
  - "3.6"
  - "3.7-dev"

services:
  - mysql

before_install:
  - mysql -u root --password="" < tests/core/storage/test_mysql.sql

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - pytest
