version: "3"

services:

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=b3_test
      - MYSQL_USER=b3test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - "3306:3306"
